services:
  - type: web
    name: backend
    env: node
    build:
      context: .
      command: npm install && npm run build
    start:
      command: node server.js
    envVars:
      - key: MONGODB_URI
        value: 'your connection string here'